### ISSUE TITLE
Cannot read property 'reloadAll' of null

### ISSUE THREAD

**Issue by jerone** [atom/dev-live-reload#13]
Editing `.less` files in Atom dev mode displays the following error in the console:
```
Uncaught TypeError: Cannot read property 'reloadAll' of null c:\Users\jerone\AppData\Local\atom\app-0.194.0\resources\app.asar\node_modules\dev-live-reload\lib\dev-live-reload.js:42 
(anonymous function) c:\Users\jerone\AppData\Local\atom\app-0.194.0\resources\app.asar\src\command-registry.js:238 
module.exports.CommandRegistry.handleCommandEvent c:\Users\jerone\AppData\Local\atom\app-0.194.0\resources\app.asar\src\command-registry.js:3 
__bind c:\Users\jerone\AppData\Local\atom\app-0.194.0\resources\app.asar\src\command-registry.js:153 
module.exports.CommandRegistry.dispatch c:\Users\jerone\AppData\Local\atom\app-0.194.0\resources\app.asar\src\window-event-handler.js:71 
(anonymous function) events.js:77 
emitOne events.js:166 
emit events.js:166
```

Confirmed this working correctly in 0.192.0. Maybe related to https://github.com/atom/atom/pull/6313

Windows 7 64-bits
Atom 0.194.0

**Comment by kevinsawicki** [comment]
Do you remember if you ran this command right at startup up? Or had Atom been running awhile?

**Comment by jerone** [comment]
I did not run this command myself. It showed up in the console after saving an edited `.less` file. 

Just tried reproducing, but it doesn't give me the error anymore. Changes to an `.less` file still aren't applied.

**Comment by kevinsawicki** [comment]
This will be fixed in the next Atom release 0.195, thanks for reporting it.

**Comment by jerone** [comment]
Great work!

**Comment by tpoisot** [comment]
Still having this issue in 1.0.19

~~~
Uncaught TypeError: Cannot read property 'reloadAll' of null
~~~
