### ISSUE TITLE
Package with activationHooks breaks live-reload

### ISSUE THREAD

**Issue by Arcanemagus** [atom/dev-live-reload#19]
It seems that somehow `linter-php` is currently breaking this, I've traced it down to when I started utilizing `activationHooks` to only activate the package when a PHP file was opened.

How this is at all relevant to this package I don't know, but installing `linter-php@1.1.0` does not exhibit the issue, while any later version does. For reference the issue where this was diagnosed can be found here: https://github.com/AtomLinter/linter-php/issues/93

Is this an Atom issue or a problem here?

**Comment by eliot-akira** [comment]
Thank you for making a note of this issue - I was editing a syntax theme and wondering why it was not being reloaded in dev mode; disabling `linter-php` made live reload work again.

**Comment by Arcanemagus** [comment]
I wish I knew enough about Atom internals to figure out where this bug was exactly... @kevinsawicki do you have any pointers? I can try to debug this if none of the people working on this package have the time.

**Comment by lee-dohm** [comment]
`activationHooks` was added with https://github.com/atom/atom/pull/7638, you may want to start by looking there?

**Comment by 50Wliu** [comment]
Seems to be working now.  Either it was fixed in the interim or with one of my recent changes to the activation lifecycle.  Please tell me if you're still seeing issues 🤞
