### ISSUE TITLE
Not working on ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [atom/dev-live-reload#20]
it seems like this package is  not working on my machine ! 
I am developing a UI theme but my changes in not showing up !

**Comment by 50Wliu** [comment]
@jonayad Can you provide some more information?
* Is Atom running in dev mode (is there a red square in the lower-left corner)?
* If you open up the developer tools (View -> Developer -> Toggle Developer Tools) and navigate to the Console section do `Reloading package` messages appear when you edit your stylesheet?
* Does pressing the keyboard shortcut <kbd>Ctrl+Alt+Shift+R</kbd> change anything?

**Comment by jonayad** [comment]
@50Wliu  sorry to tell you ! but `ctrl+alt+shift+R `bring me this :( ! 
![screenshot from 2016-03-28 22 22 42](https://cloud.githubusercontent.com/assets/12479543/14082791/bb1fd3fa-f533-11e5-9822-5b16f9c884ec.png)
it's the 4th time it happened.  but dev-live-reload sometime work fine and some time not. 
when not ! it gives me this. 
**Ans of your questions**
- yes there was a red box in the bottom left corner. 
- I can't tell properly right now is there was any messages or not.
-yes it work sometime and sometime it give the untitled window.

**Comment by lode** [comment]
I'm having the same on Ubuntu 15.10.

I see the red square. `Reloading package` does *not* appear in the console, nothing appears there when I edit a file. Nothing seems to react to that shortcut, I'm not sure what to look for though..

A normal `Alt+Ctrl+r` does reload the editor normally: I don't end up with a white screen and the changes are visible.

The console does show some warnings and errors, though I'm not sure when they started appearing and if they are related:

```
/usr/share/atom/resources/app.asar/src/text-editor-component.js:982 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
index.js:52 Window load time: 2126ms
/usr/share/atom/resources/app.asar/src/text-editor-component.js:982 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:70 The handle(7) returned by watching /home/lode/.atom/packages/ironman-syntax/styles is the same with an already watched path(/[...]/ironman-syntax/trunk/styles)
/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:70 The handle(3) returned by watching /home/lode/.atom/packages/ironman-syntax/styles/base.less is the same with an already watched path(/[...]/ironman-syntax/trunk/styles/base.less)
/usr/share/atom/resources/app.asar/node_modules/pathwatcher/lib/main.js:70 The handle(4) returned by watching /home/lode/.atom/packages/ironman-syntax/styles/colors.less is the same with an already watched path(/[...]/ironman-syntax/trunk/styles/colors.less)
```

Any clue? Is there something I can do to help debugging?

**Comment by 50Wliu** [comment]
Thanks @lode - it looks like something is wrong with the way this package is watching files.

**Comment by lode** [comment]
Yeah, I know from somewhere that such things can be a pain cross-OS.

**Comment by 50Wliu** [comment]
Looks to be the same as #17.
