### ISSUE TITLE
grammar reload

### ISSUE THREAD

**Issue by MasseGuillaume** [atom/dev-live-reload#6]
can we find a way to merge this ?

https://github.com/MasseGuillaume/atom-live-grammar-reload

**Comment by RichardSlater** [comment]
I have updated the above extension to work with the new Event API and other Atom 1.0 changes: https://github.com/RichardSlater/atom-live-grammar-reload - only issue now is two saves are required for the change to take effect - any help gratefully received.

**Comment by daviwil** [comment]
This issue was moved to atom/atom#18150
